// ============================================================================
// EDIT THIS FILE to add, remove or change the solicitors on the IRELAND
// (/ie) pages. Same shape as the UK file (lib/data/static-lawyers.ts).
//
// citySlug must match a slug in lib/ie/cities.ts
// practiceAreaSlugs must be from: immigration, family, personal-injury,
// employment, property, wills-probate
//
// Collected 28 Sep 2026 from each firm's own website (profileUrl). No
// ratings, reviews or experience figures were invented: yearsExperience is
// only set when the firm publishes a qualification/admission year (counted
// to 2026) or states a number of years itself.
//
// REGISTER CHECK — PLEASE READ
// The Law Society of Ireland's "Find a Solicitor" register
// (https://www.lawsociety.ie/find-a-solicitor/Solicitor-Firm-Search/) only
// shows results in a normal web browser, so it could not be searched
// automatically when this file was made. Each entry's `verification` says
// what WAS checked. Before promoting the /ie pages, search every firm on
// the register yourself (about 20 minutes), then set IE_REGISTER_CHECKED to
// true — the page copy then says firms "have been checked on the register".
//
// These firms have NOT consented to being listed. The /ie/listings page
// gives them a removal route.
// ============================================================================

import type { StaticLawyer } from "@/lib/data/static-lawyers";

/** Flip to true once you've searched every firm below on the Law Society of Ireland register. */
export const IE_REGISTER_CHECKED = false;

export const LSI_REGISTER_URL = "https://www.lawsociety.ie/find-a-solicitor/Solicitor-Firm-Search/";

export interface IeLawyer extends StaticLawyer {
  /** How this entry was checked (not shown on the site). */
  verification: string;
}

const LSRA_LLP_REGISTER = "Listed on the LSRA Register of Limited Liability Partnerships (21 Sep 2026)";
const FIRM_SITE = "Firm website";

function ie(entry: Omit<IeLawyer, "regulator" | "sraNumber" | "registerUrl">): IeLawyer {
  return { regulator: "LSI", sraNumber: null, registerUrl: LSI_REGISTER_URL, ...entry };
}

export const IE_LAWYERS: IeLawyer[] = [
  // ---------------------------------------------------------------- Dublin
  ie({
    id: "dublin-matthew-de-courcy",
    firmName: "KOD Lyons",
    lawyerName: "Matthew de Courcy",
    role: "Partner, Family Law",
    citySlug: "dublin",
    practiceAreaSlugs: ["family", "immigration", "employment", "personal-injury"],
    primaryPracticeArea: "family",
    bio: "Partner who leads the firm's family law department, handling child and family law matters; he also practises criminal law. Qualified in Ireland in 2010 and also qualified in England and Wales.",
    addressLine1: "31-33 Usher's Quay, Dublin 8, D08 E4YD",
    yearsExperience: 16,
    experienceNote: "16 (qualified in Ireland 2010)",
    profileUrl: "https://kodlyons.ie/team/matthew-de-courcy/",
    verification: `${FIRM_SITE}: profile page (role, qualification year); practice areas from kodlyons.ie practice pages.`,
  }),
  ie({
    id: "dublin-nora-lillis",
    firmName: "Gartlan Furey LLP",
    lawyerName: "Nora Lillis",
    role: "Partner, Private Client",
    citySlug: "dublin",
    practiceAreaSlugs: ["wills-probate", "property"],
    primaryPracticeArea: "wills-probate",
    bio: "Advises private clients and family businesses on wills, trusts, probate, succession planning and capacity matters. Former chair of the Law Society's Probate, Administration and Trusts Committee and of STEP Ireland.",
    addressLine1: "20 Fitzwilliam Square South, Dublin 2, D02 FP64",
    yearsExperience: 26,
    experienceNote: "26 (admitted 2000)",
    profileUrl: "https://www.gartlanfurey.ie/our-people/nora-lillis/",
    verification: `${FIRM_SITE}: profile page (role, admission year).`,
  }),

  // ------------------------------------------------------------------ Cork
  ie({
    id: "cork-eoin-joyce",
    firmName: "Joyce & Co Solicitors",
    lawyerName: "Eoin Joyce",
    role: "Managing Partner",
    citySlug: "cork",
    practiceAreaSlugs: ["immigration", "family", "employment", "property", "wills-probate", "personal-injury"],
    primaryPracticeArea: "immigration",
    bio: "Managing partner of a Cork firm founded in 1982, working on immigration, personal injury and property matters. The firm also has offices in Limerick and Little Island.",
    addressLine1: "9 Washington Street West, Cork, T12 FK07",
    yearsExperience: 12,
    experienceNote: "12 (qualified 2014)",
    profileUrl: "https://joycecosolicitors.ie/meet-the-team/",
    verification: `${FIRM_SITE}: 'Meet the team' page (role, qualification year, practice focus).`,
  }),
  ie({
    id: "cork-karen-walsh",
    firmName: "Walsh and Partners Solicitors LLP",
    lawyerName: "Karen Walsh",
    role: "Partner",
    citySlug: "cork",
    practiceAreaSlugs: ["property", "wills-probate", "immigration", "personal-injury"],
    primaryPracticeArea: "property",
    bio: "Founded Walsh and Partners in 2016 and works mainly on property, agricultural and commercial matters, including farm transfers, conveyancing and estate administration. Author of the book Farming and the Law.",
    addressLine1: "17 South Mall, Cork",
    yearsExperience: 17,
    experienceNote: "17 (qualified 2009)",
    profileUrl: "https://walshandpartners.ie/karen-walsh/",
    verification: `${FIRM_SITE}: profile page (role, qualification year). Also featured on lawsociety.ie (career spotlight).`,
  }),

  // -------------------------------------------------------------- Limerick
  ie({
    id: "limerick-jerry-twomey",
    firmName: "Frances Twomey & Co. Solicitors LLP",
    lawyerName: "Jerry Twomey",
    role: "Partner, Family Law",
    citySlug: "limerick",
    practiceAreaSlugs: ["family", "immigration", "employment", "property", "wills-probate", "personal-injury"],
    primaryPracticeArea: "family",
    bio: "Partner handling family law at a Limerick city-centre firm whose practice also covers immigration, employment, property, wills and probate, and personal injury.",
    addressLine1: "80 O'Connell Street, Limerick, V94 WTP3",
    yearsExperience: null,
    experienceNote: "Not published",
    profileUrl: "https://www.twomeysolicitors.ie/",
    verification: `${FIRM_SITE}: key personnel. ${LSRA_LLP_REGISTER} as "Frances Twomey & Co. LLP", 80 O'Connell Street, Limerick.`,
  }),
  ie({
    id: "limerick-michelle-hayes",
    firmName: "Hayes Solicitors Limerick",
    lawyerName: "Michelle Hayes",
    role: "Solicitor and accredited mediator",
    citySlug: "limerick",
    practiceAreaSlugs: ["employment", "family", "property", "wills-probate", "personal-injury"],
    primaryPracticeArea: "employment",
    focusNotStated: true,
    bio: "Solicitor and accredited mediator whose qualifications include diplomas in employment law, family law, commercial litigation, and planning and environmental law.",
    addressLine1: "2-3 Glentworth Street, Limerick, V94 XA9D",
    yearsExperience: null,
    experienceNote: "Not published",
    profileUrl: "https://www.hayessolicitorslimerick.com/about-solicitors",
    verification: `${FIRM_SITE}: 'About solicitors' page (name, qualifications).`,
  }),

  // ---------------------------------------------------------------- Galway
  ie({
    id: "galway-david-higgins",
    firmName: "Berwick Solicitors LLP",
    lawyerName: "David Higgins",
    role: "Partner",
    citySlug: "galway",
    practiceAreaSlugs: ["family", "employment", "immigration", "property", "wills-probate", "personal-injury"],
    primaryPracticeArea: "family",
    bio: "Galway-based partner working on family law, employment law, maritime law and business disputes. Berwick also has offices in Dublin and Ennis.",
    addressLine1: "22 Mainguard Street, Galway",
    yearsExperience: 25,
    experienceNote: "25 (qualified 2001)",
    profileUrl: "https://berwick.ie/our-people/",
    verification: `${FIRM_SITE}: 'Our people' page. ${LSRA_LLP_REGISTER}, 22 Mainguard Street, Galway.`,
  }),
  ie({
    id: "galway-susan-egan",
    firmName: "Blake & Kenny LLP",
    lawyerName: "Susan Egan",
    role: "Solicitor",
    citySlug: "galway",
    practiceAreaSlugs: ["wills-probate", "property", "personal-injury"],
    primaryPracticeArea: "wills-probate",
    bio: "Advises on wills and succession, estate planning, probate administration and residential and commercial conveyancing. Joined Blake & Kenny in 2025 after serving as managing partner of another Galway firm; holds the Law Society's Diploma in Property Tax.",
    addressLine1: "2 Saint Francis Street, Galway, H91 CA37",
    yearsExperience: 24,
    experienceNote: "24 (qualified 2002)",
    profileUrl: "https://blakeandkenny.ie/our-people/susan-egan/",
    verification: `${FIRM_SITE}: profile page. ${LSRA_LLP_REGISTER}, 2 Saint Francis Street, Galway.`,
  }),

  // ------------------------------------------------------------- Waterford
  ie({
    id: "waterford-margaret-fortune",
    firmName: "MW Keller & Son Solicitors LLP",
    lawyerName: "Margaret Fortune",
    role: "Partner",
    citySlug: "waterford",
    practiceAreaSlugs: ["family", "property", "wills-probate", "employment", "personal-injury"],
    primaryPracticeArea: "family",
    bio: "Partner handling family law, medical negligence and personal injury cases and other court work, at a Waterford firm founded in 1941.",
    addressLine1: "8 Gladstone Street, Waterford, X91 E896",
    yearsExperience: 28,
    experienceNote: "28 (qualified 1998)",
    profileUrl: "https://mwkeller.com/our-team/",
    verification: `${FIRM_SITE}: 'Our team' page (role, qualification year, practice focus).`,
  }),
  ie({
    id: "waterford-sharon-kearns",
    firmName: "Kearns Heffernan Foskin LLP",
    lawyerName: "Sharon Kearns",
    role: "Partner",
    citySlug: "waterford",
    practiceAreaSlugs: ["wills-probate", "property", "employment", "family"],
    primaryPracticeArea: "wills-probate",
    bio: "Partner since 2021, focusing on conveyancing, wills, probate and succession law.",
    addressLine1: "Otteran House, South Parade, Waterford",
    yearsExperience: 15,
    experienceNote: "15 (qualified 2011)",
    profileUrl: "https://www.khfsolicitors.com/",
    verification: `${FIRM_SITE}: legal team section (role, qualification year, practice focus).`,
  }),

  // ------------------------------------------------------------- Drogheda
  ie({
    id: "drogheda-mark-cassidy",
    firmName: "Mark Cassidy & Company Solicitors",
    lawyerName: "Mark Cassidy",
    role: "Principal",
    citySlug: "drogheda",
    practiceAreaSlugs: ["property", "family", "employment", "wills-probate", "personal-injury"],
    primaryPracticeArea: "property",
    bio: "Set up the practice in Drogheda in 2010. Handles residential and commercial property, employment and family law, and appears at Drogheda District Court and other courts in the Louth, Meath and north Dublin area. Holds the Law Society's Diploma in Property Tax.",
    addressLine1: "Hill House, St Peter's Hill, Drogheda, Co. Louth, A92 C951",
    yearsExperience: 24,
    experienceNote: "24 (entered the Roll of Solicitors 2002)",
    profileUrl: "https://www.markcassidysolicitor.ie/about/",
    verification: `${FIRM_SITE}: 'About' page (Roll year, practice areas). Address from Golden Pages listing.`,
  }),
  ie({
    id: "drogheda-rachel-nolan",
    firmName: "Nolan & Co Solicitors",
    lawyerName: "Rachel Nolan",
    role: "Principal",
    citySlug: "drogheda",
    practiceAreaSlugs: ["family", "employment", "wills-probate", "property"],
    primaryPracticeArea: "family",
    bio: "Principal solicitor working mainly in family law, criminal law, employment and probate, for clients in Louth, Meath, Cavan and Dublin.",
    addressLine1: "Tullyallen Village, Drogheda, Co. Louth",
    yearsExperience: 15,
    experienceNote: "15 (qualified 2011)",
    profileUrl: "https://www.nolansolicitors.ie/",
    verification: `${FIRM_SITE}: home page (principal, qualification year, practice areas).`,
  }),

  // --------------------------------------------------------------- Dundalk
  ie({
    id: "dundalk-steven-bellew",
    firmName: "Bellew Law",
    lawyerName: "Steven Bellew",
    role: "Founder and principal solicitor",
    citySlug: "dundalk",
    practiceAreaSlugs: ["property", "wills-probate", "employment", "personal-injury"],
    primaryPracticeArea: "property",
    focusNotStated: true,
    bio: "Founder of a Dundalk practice handling property conveyancing, wills and probate, employment law and personal injury work. Holds a Diploma in Applied Taxation.",
    addressLine1: "3 Chapel Street, Dundalk, Co. Louth, A91 XD86",
    yearsExperience: null,
    experienceNote: "Not published as a year (the firm says over a decade)",
    profileUrl: "https://bellewlaw.ie/about-company/",
    verification: `${FIRM_SITE}: 'About' page (founder, admitted to the Roll, practice areas).`,
  }),
  ie({
    id: "dundalk-jim-wallace",
    firmName: "Hamill, Wallace & Hardy LLP",
    lawyerName: "Jim Wallace",
    role: "Partner",
    citySlug: "dundalk",
    practiceAreaSlugs: ["wills-probate", "property", "employment", "personal-injury"],
    primaryPracticeArea: "wills-probate",
    focusNotStated: true,
    bio: "Partner in a Dundalk general practice whose partners handle conveyancing, litigation, wills and probate, employment and landlord and tenant matters.",
    addressLine1: "2 Demesne, Dundalk, Co. Louth",
    yearsExperience: 33,
    experienceNote: "33 (qualified 1993)",
    profileUrl: "https://www.dundalksolicitors.com/about-dundalk-solicitors.php",
    verification: `${FIRM_SITE}: 'About' page (partners, qualification years).`,
  }),

  // ---------------------------------------------------------------- Swords
  ie({
    id: "swords-patrick-power",
    firmName: "Power & Co. Solicitors",
    lawyerName: "Patrick Power",
    role: "Principal",
    citySlug: "swords",
    practiceAreaSlugs: ["family", "property", "wills-probate", "employment", "personal-injury"],
    primaryPracticeArea: "family",
    focusNotStated: true,
    bio: "Principal of a Swords general practice serving Swords, Malahide, Portmarnock and Kinsealy for over 30 years, with experience in litigation, family law, property and probate.",
    addressLine1: "61 Applewood Village, Swords, Co. Dublin",
    yearsExperience: 33,
    experienceNote: "33 (qualified 1993)",
    profileUrl: "https://ppowerandco.ie/",
    verification: `${FIRM_SITE}: home page (principal, qualification year, practice areas).`,
  }),
  ie({
    id: "swords-omar-perrozzi",
    firmName: "Hennessy & Perrozzi Solicitors",
    lawyerName: "Omar Perrozzi",
    role: "Partner",
    citySlug: "swords",
    practiceAreaSlugs: ["property", "wills-probate", "family", "personal-injury"],
    primaryPracticeArea: "property",
    focusNotStated: true,
    bio: "Partner in a Swords practice that handles residential conveyancing, estate administration and probate, family law and personal injuries.",
    addressLine1: "Town Centre Mall, Swords, Co. Dublin",
    yearsExperience: 20,
    experienceNote: "20+ (the firm says its partners have practised for over twenty years)",
    profileUrl: "https://www.hpsol.ie/",
    verification: `${FIRM_SITE}: home page (partners, experience, practice areas). DX 91 012 Swords.`,
  }),

  // ----------------------------------------------------------------- Navan
  ie({
    id: "navan-deborah-leonard",
    firmName: "Paul Brady & Co., Solicitors",
    lawyerName: "Deborah Leonard",
    role: "Solicitor",
    citySlug: "navan",
    practiceAreaSlugs: ["property", "wills-probate", "family", "employment", "personal-injury"],
    primaryPracticeArea: "property",
    bio: "Works on property and probate matters, banking law and debt collection at a Navan firm founded in 1986.",
    addressLine1: "3 Railway Street, Navan, Co. Meath",
    yearsExperience: 20,
    experienceNote: "20 (qualified 2006)",
    profileUrl: "https://www.paulbradysolicitors.ie/about/",
    verification: `${FIRM_SITE}: 'About' page (qualification date, practice focus); address from the firm's contact page.`,
  }),
  ie({
    id: "navan-daragh-fitzsimons",
    firmName: "Steen O'Reilly LLP",
    lawyerName: "Daragh Fitzsimons",
    role: "Solicitor",
    citySlug: "navan",
    practiceAreaSlugs: ["wills-probate", "property", "family", "personal-injury"],
    primaryPracticeArea: "wills-probate",
    bio: "Focuses on wills, trusts and probate at a Navan firm established in 1911 (incorporating W.O. Armstrong).",
    addressLine1: "31/34 Trimgate Street, Navan, Co. Meath",
    yearsExperience: 30,
    experienceNote: "30 (qualified 1996)",
    profileUrl: "https://www.steenoreilly.ie/",
    verification: `${FIRM_SITE}: home page (solicitors, qualification year, practice focus).`,
  }),

  // -------------------------------------------------------------- Kilkenny
  ie({
    id: "kilkenny-kieran-boland",
    firmName: "Boland and Company Solicitors",
    lawyerName: "Kieran Boland",
    role: "Principal",
    citySlug: "kilkenny",
    practiceAreaSlugs: ["wills-probate", "property", "family", "employment", "personal-injury"],
    primaryPracticeArea: "wills-probate",
    bio: "Founded the firm in 1995. Handles residential and commercial conveyancing, litigation, wills and estates.",
    addressLine1: "2 Abbey Bridge, Dean Street, Kilkenny",
    yearsExperience: 37,
    experienceNote: "37 (qualified 1989)",
    profileUrl: "https://bolandsolicitors.com/about-us",
    verification: `${FIRM_SITE}: 'About us' page (principal, qualification year, practice focus).`,
  }),
  ie({
    id: "kilkenny-mary-molloy",
    firmName: "Mary Molloy & Co. Solicitors",
    lawyerName: "Mary Molloy",
    role: "Principal Solicitor",
    citySlug: "kilkenny",
    practiceAreaSlugs: ["property", "wills-probate", "family", "employment", "personal-injury"],
    primaryPracticeArea: "property",
    bio: "Principal of a Kilkenny city practice founded in 1981, where conveyancing is the largest area of work. The firm also covers wills and estates, family law, litigation and employment law.",
    addressLine1: "2 Rose Inn Street, Kilkenny, R95 W58D",
    yearsExperience: 46,
    experienceNote: "46 (admitted 1980)",
    profileUrl: "https://marymolloysolicitor.ie/",
    verification: `${FIRM_SITE}: home page (admission year; states its solicitors are on the Roll and regulated by the Law Society of Ireland and the LSRA).`,
  }),

  // ----------------------------------------------------------------- Ennis
  ie({
    id: "ennis-pamela-clancy",
    firmName: "Cashin Clancy Solicitors LLP",
    lawyerName: "Pamela Clancy",
    role: "Partner",
    citySlug: "ennis",
    practiceAreaSlugs: ["employment", "family", "property", "wills-probate", "personal-injury"],
    primaryPracticeArea: "employment",
    bio: "Partner practising in employment law, family law, personal injuries and mental health law. The firm was formed in 2018 from the merger of Cashin & Associates and Clancy Solicitors.",
    addressLine1: "3 Francis Street, Ennis, Co. Clare, V95 Y421",
    yearsExperience: 25,
    experienceNote: "25 (qualified 2001)",
    profileUrl: "https://cashinclancy.ie/about-us/",
    verification: `${FIRM_SITE}: 'About us' page. ${LSRA_LLP_REGISTER}, 3 Francis Street, Ennis.`,
  }),
  ie({
    id: "ennis-eileen-brooks",
    firmName: "Berwick Solicitors LLP",
    lawyerName: "Eileen Brooks",
    role: "Solicitor",
    citySlug: "ennis",
    practiceAreaSlugs: ["property", "family", "employment", "wills-probate", "personal-injury"],
    primaryPracticeArea: "property",
    bio: "Solicitor at Berwick's Ennis office, focusing on residential conveyancing.",
    addressLine1: "Clare Road, Ennis, Co. Clare, V95 D36D",
    yearsExperience: 36,
    experienceNote: "36 (qualified 1990)",
    profileUrl: "https://berwick.ie/our-people/",
    verification: `${FIRM_SITE}: 'Our people' page. ${LSRA_LLP_REGISTER} (registered address in Galway).`,
  }),

  // ---------------------------------------------------------------- Carlow
  ie({
    id: "carlow-philip-vint",
    firmName: "Philip Vint & Co. Solicitors",
    lawyerName: "Philip Vint",
    role: "Principal",
    citySlug: "carlow",
    practiceAreaSlugs: ["family", "property", "wills-probate", "employment", "personal-injury"],
    primaryPracticeArea: "family",
    focusNotStated: true,
    bio: "Principal who deals with clients' matters personally across conveyancing, family law, wills and probate, litigation, employment law and personal injury.",
    addressLine1: "73 Burrin Street, Carlow",
    yearsExperience: 32,
    experienceNote: "32 (qualified 1994)",
    profileUrl: "https://www.vintsolicitors.com/",
    verification: `${FIRM_SITE}: home page (principal, qualification year, practice areas).`,
  }),
  ie({
    id: "carlow-niamh-kavanagh",
    firmName: "Farrell McElwee Solicitors LLP",
    lawyerName: "Niamh Kavanagh",
    role: "Conveyancing Solicitor",
    citySlug: "carlow",
    practiceAreaSlugs: ["property", "employment", "family", "wills-probate", "personal-injury"],
    primaryPracticeArea: "property",
    bio: "Conveyancing solicitor at a Carlow firm established in 2007 whose practice also includes employment law, family law, wills and estate planning, and personal injuries.",
    addressLine1: "1 Maryborough Street, Graiguecullen, Carlow, R93 P4A9",
    yearsExperience: null,
    experienceNote: "Not published",
    profileUrl: "https://www.fmce.ie/team.html",
    verification: `${FIRM_SITE}: team page (role). ${LSRA_LLP_REGISTER}, 1 Maryborough Street, Graiguecullen, Carlow.`,
  }),

  // ---------------------------------------------------------------- Tralee
  ie({
    id: "tralee-blathnaid-walsh",
    firmName: "O'Sullivan Reidy Solicitors",
    lawyerName: "Blathnaid Walsh",
    role: "Solicitor",
    citySlug: "tralee",
    practiceAreaSlugs: ["property", "wills-probate", "family", "employment", "personal-injury"],
    primaryPracticeArea: "property",
    bio: "Solicitor with around 20 years' experience, focusing on conveyancing, wills and probate.",
    addressLine1: "Church Street, Tralee, Co. Kerry",
    yearsExperience: 20,
    experienceNote: "20 (as stated on the firm's website)",
    profileUrl: "https://osrsolicitors.com/about-us/",
    verification: `${FIRM_SITE}: 'About us' page (experience, practice focus).`,
  }),
  ie({
    id: "tralee-siobhan-leahy",
    firmName: "Cadogan O'Regan LLP",
    lawyerName: "Siobhán Leahy",
    role: "Solicitor",
    citySlug: "tralee",
    practiceAreaSlugs: ["wills-probate", "property", "family", "personal-injury"],
    primaryPracticeArea: "wills-probate",
    bio: "Practises in conveyancing, wills and probate, and personal injuries at a Tralee firm established in 2004.",
    addressLine1: "22 Denny Street, Tralee, Co. Kerry, V92 XPN0",
    yearsExperience: 19,
    experienceNote: "19 (admitted 2007)",
    profileUrl: "https://www.cador.ie/",
    verification: `${FIRM_SITE}: home page (admission year, practice focus). ${LSRA_LLP_REGISTER}, 22 Denny St, Tralee.`,
  }),

  // ------------------------------------------------------------------ Naas
  ie({
    id: "naas-david-osborne",
    firmName: "Osborne Denieffe LLP",
    lawyerName: "David Osborne",
    role: "Managing Partner",
    citySlug: "naas",
    practiceAreaSlugs: ["property", "family", "employment", "wills-probate", "personal-injury"],
    primaryPracticeArea: "property",
    focusNotStated: true,
    bio: "Managing partner of a Naas firm established in 2000. The firm covers property and conveyancing, family law, employment, probate and estate planning, personal injury, and agricultural and bloodstock law.",
    addressLine1: "Abbey Moat House, Abbey Street, Naas, Co. Kildare, W91 NN9V",
    yearsExperience: null,
    experienceNote: "Not published",
    profileUrl: "https://www.osbornedenieffe.ie/our-team-solicitors-naas-newbridge-kildare/",
    verification: `${FIRM_SITE}: team page and home page (role, practice areas).`,
  }),
  ie({
    id: "naas-stephen-walsh",
    firmName: "Stephen Walsh & Co. Solicitors",
    lawyerName: "Stephen Walsh",
    role: "Principal Solicitor",
    citySlug: "naas",
    practiceAreaSlugs: ["wills-probate", "property", "family", "personal-injury"],
    primaryPracticeArea: "wills-probate",
    focusNotStated: true,
    bio: "Principal of a Naas practice covering serious injury and medical negligence, mental capacity law, property and conveyancing, commercial law, and wills and probate.",
    addressLine1: "38 South Main Street, Naas, Co. Kildare",
    yearsExperience: null,
    experienceNote: "Not published",
    profileUrl: "https://stephenwalshsolicitors.ie/",
    verification: `${FIRM_SITE}: home page and contact page (principal, address, practice areas).`,
  }),

  // --------------------------------------------------------------- Athlone
  ie({
    id: "athlone-john-ocarroll",
    firmName: "Mellotte O'Carroll Solicitors LLP",
    lawyerName: "John O'Carroll",
    role: "Partner",
    citySlug: "athlone",
    practiceAreaSlugs: ["property", "employment", "wills-probate", "personal-injury"],
    primaryPracticeArea: "property",
    bio: "Partner focusing on residential and commercial conveyancing. The firm also has an office in Mountbellew, Co. Galway.",
    addressLine1: "Pearse Street, Athlone, Co. Westmeath, N37 F728",
    yearsExperience: null,
    experienceNote: "Not published",
    profileUrl: "https://mocsolicitors.ie/about-us/our-members/",
    verification: `${FIRM_SITE}: 'Our members' page (role, practice focus); the firm states it has been authorised and registered as an LLP by the LSRA since 23 April 2020.`,
  }),
  ie({
    id: "athlone-clodagh-shine",
    firmName: "Tormeys Solicitors LLP",
    lawyerName: "Clodagh Shine",
    role: "Partner",
    citySlug: "athlone",
    practiceAreaSlugs: ["wills-probate", "property", "employment", "personal-injury"],
    primaryPracticeArea: "wills-probate",
    bio: "Partner since 2018, working on wills, probate, conveyancing, property and commercial law. Treasurer of the Midland Bar Association.",
    addressLine1: "Castle Street, Athlone, Co. Westmeath, N37 D960",
    yearsExperience: 20,
    experienceNote: "20 (qualified 2006)",
    profileUrl: "https://tormeys.ie/team/clodagh-shine/",
    verification: `${FIRM_SITE}: profile page (role, qualification year, practice focus).`,
  }),

  // ----------------------------------------------------------------- Sligo
  ie({
    id: "sligo-valerie-kearins",
    firmName: "Valerie Kearins Solicitors",
    lawyerName: "Valerie Kearins",
    role: "Principal",
    citySlug: "sligo",
    practiceAreaSlugs: ["personal-injury", "property", "wills-probate", "employment", "family"],
    primaryPracticeArea: "personal-injury",
    bio: "Principal of a Sligo practice handling personal injury and medical negligence cases, conveyancing, wills and probate, employment and family law.",
    addressLine1: "Unit 2, High Market House, Old Market Street, Sligo",
    yearsExperience: 17,
    experienceNote: "17+ (the firm says over 17 years advising on personal injury cases)",
    profileUrl: "https://vkearinssolicitor.ie/",
    verification: `${FIRM_SITE}: home page (name, practice areas, experience).`,
  }),
  ie({
    id: "sligo-elaine-coghill",
    firmName: "Hickey Coghill Solicitors LLP",
    lawyerName: "Elaine Coghill",
    role: "Partner",
    citySlug: "sligo",
    practiceAreaSlugs: ["family", "property", "wills-probate", "employment", "personal-injury"],
    primaryPracticeArea: "family",
    focusNotStated: true,
    bio: "Partner at a Sligo firm whose work covers property and conveyancing, family law, probate, litigation, employment law and accident cases.",
    addressLine1: "Wine Street, Sligo",
    yearsExperience: 22,
    experienceNote: "22 (qualified 2004)",
    profileUrl: "https://www.hickeycoghillsolicitors.ie/about/",
    verification: `${FIRM_SITE}: 'About' page (partner, qualification year).`,
  }),

  // ----------------------------------------------------------- Letterkenny
  ie({
    id: "letterkenny-patsy-gallagher",
    firmName: "Gallagher & Brennan Solicitors",
    lawyerName: "Patsy Gallagher",
    role: "Solicitor",
    citySlug: "letterkenny",
    practiceAreaSlugs: ["family", "employment", "property", "wills-probate"],
    primaryPracticeArea: "family",
    bio: "Handles civil and criminal litigation, employment law and family law at a Letterkenny practice founded in 2006.",
    addressLine1: "House B, Carnamuggagh Upper, Kilmacrennan Road, Letterkenny, Co. Donegal, F92 V050",
    yearsExperience: null,
    experienceNote: "Not published",
    profileUrl: "https://gallagherbrennan.ie/",
    verification: `${FIRM_SITE}: home page (named solicitors and their areas).`,
  }),
  ie({
    id: "letterkenny-dominic-brennan",
    firmName: "Gallagher & Brennan Solicitors",
    lawyerName: "Dominic Brennan",
    role: "Solicitor",
    citySlug: "letterkenny",
    practiceAreaSlugs: ["wills-probate", "property", "family", "employment"],
    primaryPracticeArea: "wills-probate",
    bio: "Handles property transactions, wills, probate and estate administration, and advises on gift and inheritance tax and stamp duty.",
    addressLine1: "House B, Carnamuggagh Upper, Kilmacrennan Road, Letterkenny, Co. Donegal, F92 V050",
    yearsExperience: null,
    experienceNote: "Not published",
    profileUrl: "https://gallagherbrennan.ie/",
    verification: `${FIRM_SITE}: home page (named solicitors and their areas).`,
  }),

  // --------------------------------------------------------------- Wexford
  ie({
    id: "wexford-seamas-turner",
    firmName: "M J O'Connor LLP",
    lawyerName: "Seamas Turner",
    role: "Partner",
    citySlug: "wexford",
    practiceAreaSlugs: ["family", "property", "wills-probate", "personal-injury"],
    primaryPracticeArea: "family",
    bio: "Partner handling family law and divorce, civil and commercial litigation and personal injuries, at a firm that has practised since 1888.",
    addressLine1: "Drinagh, Wexford, Y35 E76D",
    yearsExperience: 34,
    experienceNote: "34 (qualified 1992)",
    profileUrl: "https://mjoc.ie/our-people/",
    verification: `${FIRM_SITE}: 'Our people' page (role, office, qualification year, practice focus).`,
  }),
  ie({
    id: "wexford-eleanor-ofarrell",
    firmName: "Kirwan & Kirwan LLP Solicitors",
    lawyerName: "Eleanor O'Farrell",
    role: "Partner",
    citySlug: "wexford",
    practiceAreaSlugs: ["property", "wills-probate", "family", "personal-injury"],
    primaryPracticeArea: "property",
    focusNotStated: true,
    bio: "Partner since 2017 at a firm that has practised in Wexford town since 1864. The firm covers court work, property, probate and wills, family law and injury cases.",
    addressLine1: "Cornmarket, Wexford",
    yearsExperience: 17,
    experienceNote: "17 (qualified 2009)",
    profileUrl: "https://kirwanandkirwan.com/about-kirwan-kirwan/",
    verification: `${FIRM_SITE}: 'About' page (partners, qualification years).`,
  }),

  // ------------------------------------------------------------- Mullingar
  ie({
    id: "mullingar-matthew-johnston",
    firmName: "Nooney & Dowdall LLP Solicitors",
    lawyerName: "Matthew Johnston",
    role: "Managing Partner",
    citySlug: "mullingar",
    practiceAreaSlugs: ["wills-probate", "property", "family", "employment"],
    primaryPracticeArea: "wills-probate",
    bio: "Managing partner working on probate and estate administration, wills and estate planning, conveyancing, property litigation and capacity law. Completed the STEP Ireland / Law Society Diploma in Trust and Estate Planning in 2023.",
    addressLine1: "16 Mary Street, Mullingar, Co. Westmeath, N91 XY64",
    yearsExperience: 30,
    experienceNote: "30 (admitted to the Roll 1996)",
    profileUrl: "https://mullingarsolicitors.ie/about-us/matthew-johnston-partner/",
    verification: `${FIRM_SITE}: profile page (role, admission year, practice areas).`,
  }),
  ie({
    id: "mullingar-aisling-penrose",
    firmName: "Kelly Caulfield Shaw Solicitors",
    lawyerName: "Aisling Penrose",
    role: "Solicitor",
    citySlug: "mullingar",
    practiceAreaSlugs: ["property", "wills-probate", "family", "employment"],
    primaryPracticeArea: "property",
    bio: "Works on conveyancing, probate and wills, landlord and tenant law and debt collection. Joined the firm as an apprentice in 2012.",
    addressLine1: "1 Chapterhouse, Friars Mill Road, Mullingar, Co. Westmeath, N91 RT68",
    yearsExperience: 12,
    experienceNote: "12 (qualified 2014)",
    profileUrl: "https://kcs.ie/staff-folder/aisling-penrose-kelly-caulfield-shaw-solicitors-mullingar-westmeath.html",
    verification: `${FIRM_SITE}: profile page (role, qualification year, practice areas).`,
  }),

  // ------------------------------------------------------------- Castlebar
  ie({
    id: "castlebar-augusta-tuohy",
    firmName: "Michael Moran Solicitors LLP",
    lawyerName: "Augusta Tuohy",
    role: "Partner",
    citySlug: "castlebar",
    practiceAreaSlugs: ["family", "property", "wills-probate", "personal-injury"],
    primaryPracticeArea: "family",
    bio: "Partner practising in family law, litigation including personal injuries claims, and residential and commercial conveyancing and commercial leases.",
    addressLine1: "Mountain View, Knockaphunta, Castlebar, Co. Mayo, F23 T283",
    yearsExperience: 20,
    experienceNote: "20 (qualified 2006)",
    profileUrl: "https://michaelmoransolicitors.ie/team.html",
    verification: `${FIRM_SITE}: team page (role, qualification year, practice focus). Address from Golden Pages / irish-pages listings.`,
  }),
  ie({
    id: "castlebar-joanna-jordan",
    firmName: "Jordan and Kennelly Solicitors",
    lawyerName: "Joanna Jordan",
    role: "Principal",
    citySlug: "castlebar",
    practiceAreaSlugs: ["wills-probate", "property"],
    primaryPracticeArea: "wills-probate",
    bio: "Principal of a Castlebar practice focused on wills, probate, trust and estate planning, and conveyancing. A member of STEP and a Registered Trust and Estate Practitioner (TEP).",
    addressLine1: "New Antrim Street, Castlebar, Co. Mayo, F23 VK88",
    yearsExperience: null,
    experienceNote: "Not published",
    profileUrl: "https://www.jks.ie/",
    verification: `${FIRM_SITE}: home page (principal, practice areas).`,
  }),
];
